version: '3.8'

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile-flask
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development

  streamlit_app:
    build:
      context: .
      dockerfile: Dockerfile-streamlit
    container_name: streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - flask_app
